import random
from pathlib import Path
def gen_element() ->  int:
    #  key <- an integer that is drawn uniformly at random from the range [0,10^7]
    # Return key as the generated element.
    return random.randrange(0, 10**7 + 1)


def gen_push() -> str:
    # is a push operation of an element in the form of (1, key), where 1 indicates that this operation is a push, 
    # and key is the element to be pushed.
    # Its detailed steps are:
    # - x <- a new element of key generated by invoking gen_element()
    # - return (1, x), a push for element x
    return

def gen_pop() -> str:
    # is a pop operation in the form of (2), where 2 indicates that this operation is a pop.
    # Return 2, a pop operation 
    return

def gen_getTop() -> str:
    # is a getTop operation in the form of (3), where 3 indicates that this operation is a getTop.
    # Its detailed steps are:
    # Return 3, a getTop operation.
    return 

# write data to file - creates a dir if required
def write_to_file(filename: str, data: list[str], base_dir: Path = Path.cwd() / "experiments"):
    path = base_dir / filename
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as file:
        file.writelines(f"{line}\n" for line in data)

